// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNqBXjieC1RVOKqg_LNDaeQ4bwFJnSFMs',
    appId: '1:60851299608:web:9e4f8eaa79038fc000ea6d',
    messagingSenderId: '60851299608',
    projectId: 'blog-it--workshop',
    authDomain: 'blog-it--workshop.firebaseapp.com',
    storageBucket: 'blog-it--workshop.firebasestorage.app',
    measurementId: 'G-SV7GTC75MB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-pbBfn5e4Dm8c9P5p9_sgnwWPTCOqgdE',
    appId: '1:60851299608:android:e932e1a778a53ce900ea6d',
    messagingSenderId: '60851299608',
    projectId: 'blog-it--workshop',
    storageBucket: 'blog-it--workshop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiv9S_0zweqk1D-xxOYKAts3tfxMPyWMw',
    appId: '1:60851299608:ios:0a2901ae0a894a1200ea6d',
    messagingSenderId: '60851299608',
    projectId: 'blog-it--workshop',
    storageBucket: 'blog-it--workshop.firebasestorage.app',
    iosBundleId: 'com.example.blogitGoogleworkshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiv9S_0zweqk1D-xxOYKAts3tfxMPyWMw',
    appId: '1:60851299608:ios:0a2901ae0a894a1200ea6d',
    messagingSenderId: '60851299608',
    projectId: 'blog-it--workshop',
    storageBucket: 'blog-it--workshop.firebasestorage.app',
    iosBundleId: 'com.example.blogitGoogleworkshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNqBXjieC1RVOKqg_LNDaeQ4bwFJnSFMs',
    appId: '1:60851299608:web:d3231cff834d9b7d00ea6d',
    messagingSenderId: '60851299608',
    projectId: 'blog-it--workshop',
    authDomain: 'blog-it--workshop.firebaseapp.com',
    storageBucket: 'blog-it--workshop.firebasestorage.app',
    measurementId: 'G-32MG7Q0NZK',
  );

}